services:
  app:
    build:
      context: .
    image: node-app:latest
    env_file: .env
    ports: 
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/src/app
    environment:
      - NODE_ENV=development
      - PG_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MONGO_DATABASE_URL=mongodb://mongo:27017
    networks:
      - web_net
      - postgres_subnet
      - mongo_subnet
    depends_on:
      - postgres
      - mongo

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - '443:443'
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/secrets/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/secrets/certs:/etc/nginx/certs:ro
      - ./static:/usr/share/nginx/static:ro
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - web_net

    
  postgres:
    image: postgres:latest
    networks:
      - postgres_subnet
    ports:
      - ${DEV_POSTGRES_PORT:-}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
  
  mongo:
    image: mongo:latest
    networks:
      - mongo_subnet
    ports:
      - ${DEV_MONGO_PORT:-}
    volumes:
      - mongo-data:/data/db

networks:
  web_net:
    driver: bridge
  mongo_subnet:       # виправлено назву, без дефісу і узгоджено з services
    driver: bridge
  postgres_subnet:
    driver: bridge
volumes:
  postgres-data:
  mongo-data:
